### ISSUE TITLE
TypeError: Cannot read property 'user' of undefined

### ISSUE THREAD

**Issue by julianuphoff** [getsentry/raven-node#281]
Sometimes I receive this error in sentry: 

```
TypeError: Cannot read property 'user' of undefined
  File "/path/to/node_modules/raven/lib/client.js", line 152, col 49, in Raven.process
    kwargs.user = extend({}, this._globalContext.user, domainContext.user, kwargs.user);
  File "/path/to/node_modules/raven/lib/client.js", line 246, col 12, in null.<anonymous>
    self.process(eventId, kw, cb);
  File "/path/to/node_modules/raven/lib/parsers.js", line 52, col 5, in null.<anonymous>
    cb(kwargs);
  File "/path/to/node_modules/raven/lib/utils.js", line 199, col 30, in null.<anonymous>
    if (--callbacks === 0) cb(frames);
  File "fs.js", line 445, col 3, in FSReqWrap.readFileAfterClose [as oncomplete]

```

**Comment by LewisJEllis** [comment]
Can you post your setup/init code? The only way I can imagine this happening as described is if raven-node is not being initialized correctly (maybe missing `.config()` call).

**Comment by blakebyrnes** [comment]
I think I may have just figured out that this is happening only in our submodule that also uses raven, but isn't being initialized correctly inside the module.

**Comment by wreckah** [comment]
I had the same problem and investigated that `this._globalContext` is `undefined`. Then I read documentation twice and realized that I forgot to add `Raven.config('__DSN__').install();` when updated Raven to 1.x version.

**Comment by LewisJEllis** [comment]
Cool, thanks for the report - in that case I'm gonna go ahead and close this as a case of misconfiguration/lack of initialization. I'll add a check to capturing/processing of exceptions that make sure initialization has happened so the error message can be better.

**Comment by Prior99** [comment]
This still happens, when the setup code is not executed properly and can be quite confusing.

```
TypeError: Cannot read property 'user' of undefined
    at Raven.process (/home/prior/repositories/go3/node_modules/raven/lib/client.js:218:50)
    at /home/prior/repositories/go3/node_modules/raven/lib/client.js:395:12
    at /home/prior/repositories/go3/node_modules/raven/lib/parsers.js:55:5
    at /home/prior/repositories/go3/node_modules/raven/lib/utils.js:362:5
    at /home/prior/repositories/go3/node_modules/raven/lib/utils.js:272:35
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
error:  TypeError: Cannot read property 'user' of undefined
    at Raven.process (/home/prior/repositories/go3/node_modules/raven/lib/client.js:218:50)
    at /home/prior/repositories/go3/node_modules/raven/lib/client.js:395:12
    at /home/prior/repositories/go3/node_modules/raven/lib/parsers.js:55:5
    at /home/prior/repositories/go3/node_modules/raven/lib/utils.js:362:5
    at /home/prior/repositories/go3/node_modules/raven/lib/utils.js:272:35
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```
