### ISSUE TITLE
disabled sentry swallows uncaught exceptions

### ISSUE THREAD

**Issue by francisdb** [getsentry/raven-node#288]
When sentry is set up with DSN undefined without calling install()

```
node app.js
raven@1.1.3 alert: no DSN provided, error reporting disabled
module.js:472
    throw err;
    ^

Error: Cannot find module 'hot-shots'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    ...
```

When sentry is set up with DSN undefined and install() called

```
node app.js
raven@1.1.3 alert: no DSN provided, error reporting disabled
raven@1.1.3 alert: uncaughtException: 516d72bd0b9b4cb7abcad0cb692af94d
```

Why is there nothing logged to the console here?

**Comment by LewisJEllis** [comment]
This is a symptom of #257. Work on that is in progress.
