### ISSUE TITLE
Raven throws "XMLHttpRequest is not defined"

### ISSUE THREAD

**Issue by florianb** [getsentry/raven-node#298]
Today i integrated Raven the first time into an Node-project we're developing. Unfortunately Raven.js crashes on the first caught `unhandledRejection`:

```
<<project_path>>/node_modules/raven-js/src/raven.js:365
                throw ex1;
                ^

ReferenceError: XMLHttpRequest is not defined
    at Raven._makeRequest (<<project_path>>/node_modules/raven-js/src/raven.js:1578:27)
    at Raven._sendProcessedPayload (<<project_path>>/node_modules/raven-js/src/raven.js:1546:56)
    at Raven._send (<<project_path>>/node_modules/raven-js/src/raven.js:1492:14)
    at Raven._processException (<<project_path>>/node_modules/raven-js/src/raven.js:1308:14)
    at Raven._handleStackInfo (<<project_path>>/node_modules/raven-js/src/raven.js:1214:14)
    at Raven.captureException (<<project_path>>/node_modules/raven-js/src/raven.js:362:18)
    at process.on.err (<<project_path>>/lib/index.js:29:18)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at processEmit [as emit] (<<project_path>>/node_modules/signal-exit/index.js:155:32)
    at emitPendingUnhandledRejections (internal/process/promises.js:85:22)
    at runMicrotasksCallback (internal/process/next_tick.js:61:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

I actually integrated Raven like this:

```js
import Raven from 'raven-js'
import moggie from 'moggie'

import server from './server-command'
import network from './network-command'

Raven
	.config('https://<<token>>@sentry.io/<<token>>')
	.install()

process.on('unhandledRejection', err => {
	Raven.captureException(err)
})

export default {
	run: () => {
		try {
			moggie({
				minimistOptions: {
					'--': true
				},
				subcommands: {
					server,
					network
				}
			})
		} catch (err) {
			Raven.captureException(err)
		}
	}
}

```

We're running it in the following environment:

```
Node.js v7.4.0

raven-js@3.12.1

ava@0.18.2
babel-core@6.24.0
babel-preset-env@1.2.2
chalk@1.1.3
enquirer@0.4.1
enquirer-prompts@0.1.1
esdoc@0.5.2
listr@0.11.0
moggie@1.0.2
nock@9.0.9
nyc@10.1.2
printen@1.0.0-2
xo@0.17.1
```

**Comment by benvinegar** [comment]
You should be using `raven-node`, not `raven-js` for Node projects. `raven-js` is for browser JavaScript.

```
npm install raven
```

```javascript
import Raven from 'raven';
```

**Comment by florianb** [comment]
Oh man - embarrassing. Sorry for the noise and thanks for your help! ❤️
