### ISSUE TITLE
Node.js process crashes after "raven-node" handles an uncaught Node exception

### ISSUE THREAD

**Issue by cooolwire** [getsentry/raven-node#386]
**What is the current behavior?**

My NodeJS process (an Electron app) crashes entirely when catching an uncaught exception.

I am using `raven@2.2.1` and `node@7.2.1`

Here is the `npm-debug.log`:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/cooolwire/.nvm/versions/node/v7.2.1/bin/node',
1 verbose cli   '/Users/cooolwire/.nvm/versions/node/v7.2.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@3.10.10
3 info using node@v7.2.1
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle electron@0.0.1~predev: electron@0.0.1
6 silly lifecycle electron@0.0.1~predev: no script for predev, continuing
7 info lifecycle electron@0.0.1~dev: electron@0.0.1
8 verbose lifecycle electron@0.0.1~dev: unsafe-perm in lifecycle true
9 verbose lifecycle electron@0.0.1~dev: PATH: /Users/cooolwire/.nvm/versions/node/v7.2.1/lib/node_modules/npm/bin/node-gyp-bin:/Users/cooolwire/src/app/packages/electron/node_modules/.bin:/Users/cooolwire/.rbenv/shims:/Users/cooolwire/.nvm/versions/node/v7.2.1/bin:/usr/local/bin:/usr/local/sbin:/Users/cooolwire/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/npm/bin
10 verbose lifecycle electron@0.0.1~dev: CWD: /Users/cooolwire/src/app/packages/electron
11 silly lifecycle electron@0.0.1~dev: Args: [ '-c', 'cross-env START_HOT=1 npm run hot-updates-server' ]
12 silly lifecycle electron@0.0.1~dev: Returned: code: 1  signal: null
13 info lifecycle electron@0.0.1~dev: Failed to exec dev script
14 verbose stack Error: electron@0.0.1 dev: `cross-env START_HOT=1 npm run hot-updates-server`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/cooolwire/.nvm/versions/node/v7.2.1/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/cooolwire/.nvm/versions/node/v7.2.1/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid electron@0.0.1
16 verbose cwd /Users/cooolwire/src/app/packages/electron
17 error Darwin 16.6.0
18 error argv "/Users/cooolwire/.nvm/versions/node/v7.2.1/bin/node" "/Users/cooolwire/.nvm/versions/node/v7.2.1/bin/npm" "run" "dev"
19 error node v7.2.1
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error electron@0.0.1 dev: `cross-env START_HOT=1 npm run hot-updates-server`
22 error Exit status 1
23 error Failed at the electron@0.0.1 dev script 'cross-env START_HOT=1 npm run hot-updates-server'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the electron package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     cross-env START_HOT=1 npm run hot-updates-server
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs electron
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls electron
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

The exception, however, does get published to my Sentry.io account.

**What is the expected behavior?**

raven-node should catch the uncaught exception, publish it to my Sentry.io account, and the app should continue running.

**Comment by kamilogorek** [comment]
Unfortunately, I don't see anything useful in the logs here. You can try to setup fatal error handler and see what's causing the issue – https://docs.sentry.io/clients/node/usage/#global-fatal-error-handler

**Comment by cooolwire** [comment]
Hi @kamilogorek,

Thank you for the prompt reply.

That fixed my issue. I just read the section of the doc you sent and now understand why it was existing.
