### ISSUE TITLE
How can I prevent process crash when it gets an `uncaughtException` 

### ISSUE THREAD

**Issue by leizongmin** [getsentry/raven-node#411]
**What is the current behavior?**

Version: `raven@2.1.2`

Run the following code:

```javascript
var Raven = require('raven');
Raven.config('__your_dsn_here__', {
  environment: process.env.NODE_ENV || 'dev',
}).install();

process.on('uncaughtException', function (err) {
  console.log('uncaughtException', err);
});

setInterval(function () {}, 2000);

throw new Error('aaa');
```

It outputs the result and crashed:

```
uncaughtException Error: aaa
    at Object.<anonymous> (/tmp/test.js:12:7)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
Error: aaa
    at Object.<anonymous> (/tmp/test.js:12:7)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**What is the expected behavior?**

When it occurs an uncaught exception, I expected to handle the `uncaughtException` event by myself, **I don't want to crash the running process**. As far as I know the `raven@1.1.x` works well for me before.

So when using `raven@2.1.2`, how can I prevent process crash if it gets an `uncaughtException`

**Comment by zengming00** [comment]
met the same problem

**Comment by kamilogorek** [comment]
@leizongmin @zengming00 please refer to the docs here https://docs.sentry.io/clients/node/usage/#global-fatal-error-handler
Feel free to reopen the issue if the it's not enough :)
