### ISSUE TITLE
Circular/infinite loop encountered when passing model instance in `context` of `captureException` call that contains a circular reference

### ISSUE THREAD

**Issue by newhouse** [getsentry/raven-node#443]
Hi there, I'm using `raven` `2.4.2`.

When I pass something that apparently contains a circular reference to the `context` of a `captureException` call, raven goes down the rabbit hole and I get a `Maximum call stack size exceeded` error. It does NOT seem to be of importance that I am passing a non-`Error` instance as the first argument to `captureException`, but in this example I am.

Psuedocodish:
```
const client = Raven.config('xxxx', {environment: 'debug'}).install();
const myInstance = new SomeModel(); // This may contain circular references

const jsonError = { message: 'you don wrong' };
const context = {
  extra: {
    myInstance: myInstance
  }
};

console.log(myInstance); // no problems
console.log(myInstance.toJSON()); // no problems
console.log(JSON.stringify(myInstance)); // no problems

client.captureException(jsonError, context); // Circular reference and blows up

```

Here's the stack trace:
```
RangeError: Maximum call stack size exceeded
    at baseClone (/Users/newhouse/projects/revolt/broadcast/node_modules/lodash/_baseClone.js:87:19)
    at /Users/newhouse/projects/revolt/broadcast/node_modules/lodash/_baseClone.js:148:30
    at arrayEach (/Users/newhouse/projects/revolt/broadcast/node_modules/lodash/_arrayEach.js:15:9)
    at baseClone (/Users/newhouse/projects/revolt/broadcast/node_modules/lodash/_baseClone.js:142:3)
    at /Users/newhouse/projects/revolt/broadcast/node_modules/lodash/_baseClone.js:148:30
    at arrayEach (/Users/newhouse/projects/revolt/broadcast/node_modules/lodash/_arrayEach.js:15:9)
    at baseClone (/Users/newhouse/projects/revolt/broadcast/node_modules/lodash/_baseClone.js:142:3)
    at /Users/newhouse/projects/revolt/broadcast/node_modules/lodash/_baseClone.js:148:30
    at arrayEach (/Users/newhouse/projects/revolt/broadcast/node_modules/lodash/_arrayEach.js:15:9)
    at baseClone (/Users/newhouse/projects/revolt/broadcast/node_modules/lodash/_baseClone.js:142:3)
    at /Users/newhouse/projects/revolt/broadcast/node_modules/lodash/_baseClone.js:148:30
    at arrayEach (/Users/newhouse/projects/revolt/broadcast/node_modules/lodash/_arrayEach.js:15:9)
    at baseClone (/Users/newhouse/projects/revolt/broadcast/node_modules/lodash/_baseClone.js:142:3)
    at /Users/newhouse/projects/revolt/broadcast/node_modules/lodash/_baseClone.js:148:30
    at arrayEach (/Users/newhouse/projects/revolt/broadcast/node_modules/lodash/_arrayEach.js:15:9)
    at baseClone (/Users/newhouse/projects/revolt/broadcast/node_modules/lodash/_baseClone.js:142:3)
    at cloneDeep (/Users/newhouse/projects/revolt/broadcast/node_modules/lodash/cloneDeep.js:26:10)
    at toJsonObject (/Users/newhouse/projects/revolt/broadcast/node_modules/objection/lib/model/modelToJson.js:103:12)
    at assignJsonValue (/Users/newhouse/projects/revolt/broadcast/node_modules/objection/lib/model/modelToJson.js:73:19)
    at toExternalJsonImpl (/Users/newhouse/projects/revolt/broadcast/node_modules/objection/lib/model/modelToJson.js:51:5)
    at toJson (/Users/newhouse/projects/revolt/broadcast/node_modules/objection/lib/model/modelToJson.js:8:16)
    at Credential.toJSON (/Users/newhouse/projects/revolt/broadcast/node_modules/objection/lib/model/Model.js:209:12)
    at Credential.toJSON (/Users/newhouse/projects/revolt/broadcast/models/Base.js:201:37)
    at Credential.toJSON (/Users/newhouse/projects/revolt/broadcast/models/Credential.js:888:31)
    at JSON.stringify (<anonymous>)
    at stringify (/Users/newhouse/projects/revolt/broadcast/node_modules/raven/vendor/json-stringify-safe.js:18:15)
    at Raven.send (/Users/newhouse/projects/revolt/broadcast/node_modules/raven/lib/client.js:309:19)
    at Raven.process (/Users/newhouse/projects/revolt/broadcast/node_modules/raven/lib/client.js:295:12)
    at /Users/newhouse/projects/revolt/broadcast/node_modules/raven/lib/client.js:402:12
    at /Users/newhouse/projects/revolt/broadcast/node_modules/raven/lib/parsers.js:55:5
    at Object.parseStack (/Users/newhouse/projects/revolt/broadcast/node_modules/raven/lib/utils.js:307:12)
    at Object.parseError (/Users/newhouse/projects/revolt/broadcast/node_modules/raven/lib/parsers.js:17:9)
    at Raven.captureException (/Users/newhouse/projects/revolt/broadcast/node_modules/raven/lib/client.js:401:13)
    at Timeout._onTimeout (/Users/newhouse/projects/revolt/broadcast/helpers/errors.js:125:21)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
```

Perhaps it stems from the use of `json-stringify-safe`?

**Comment by kamilogorek** [comment]
It seems like a strange clash between your ORM and JSON.stringify, as you can clearly see that the issue originates from some models cyclical relations. Can you provide the code for `Credential` and `Base` models that you use? Or in the best possible scenario, the repro case that I could use?

**Comment by newhouse** [comment]
Thanks for the reply.

Does not the fact that raven is the only style of stringifying that has trouble with the instance (as demonstrated by the multiple ways it is done in the example) point more towards something with raven as the culprit?

Either way, let me see if I can pull something together for you. I'll ask about this over at Objection, too.

**Comment by kamilogorek** [comment]
I agree that we should take a look at this (thus I asked for the repro case), however, we are calling methods from the ORM itself which is looping around.
Anyway, I'm more than happy to see if I can figure out what's going on in there. I just need to a code example and I should be ready to go :)

**Comment by newhouse** [comment]
working on repro today.

**Comment by newhouse** [comment]
Ugh. I can't reproduce it without putting way too much of my entire app in here. If it comes up again and I can isolate in a more standalone-friendly way, I will come back to this. Thanks anyways!
